---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: webapps
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app
    version: blue # Initially point to the Blue version