---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: mysql-storage  # Matches the PV's label
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi