---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: webapps
type: Opaque
data:
  DB_USER: cm9vdA==           # mysql
  DB_PASSWORD: VGVzdEAxMjM=   # Test@123
  DB_NAME: dGVzdF9kYg==       # test_db