apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodejs-app-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
